### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by Explore-c** [saucer-man/apkinfo#2]

**Comment by Explore-c** [comment]
> ### 报错信息
> Traceback (most recent call last): File "apkinfo.py", line 6, in from apkutils import APK File "F:\python\lib\site-packages\apkutils__init__.py", line 1, in from apkutils.apk import * File "F:\python\lib\site-packages\apkutils\apk.py", line 158 if addr := item.get("android:icon"): ^ SyntaxError: invalid syntax
> 
> ### 环境
> py3.7 win10 apkutils1.0.2
